version: 0.2

phases:

  install:
    commands:
      - npm install
      - npm install serverless -g

  build:
    commands:
      - npm test
      - cd hello-world
      - serverless package

artifacts:
  files:
    - buildspecs/deploy-qa.buildspec.yml
    - hello-world/.serverless/**/*
    - hello-world/serverless.yml
